[package]
name = "openvair_installer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
anyhow = "1.0"
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
toml_edit = "0.22"
regex = "1.0"

[dev-dependencies]
tempfile = "3.0"
